apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 20

  selector:
    matchLabels:
      type: app
      service: nginx-demo
  template:
    metadata:
      labels:
        type: app
        service: nginx-demo
    spec:
      containers:
      - name: nginx-demo
        image: jamesby99/nginx-unbuntu
        livenessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  type: NodePort
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    type: app
    service: nginx-demo
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-execise
spec:
  maxReplicas: 30
  minReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: nginx-demo
  targetCPUUtilizationPercentage: 80